### ISSUE TITLE
Review total amount rounding when tokens are chosen

### ISSUE THREAD

**Issue by noeliaSD** [status-im/feature-specs#73]
Since in the new currency selector design it is allowed to select a token, now the total wallet amoud rounding should be reviewed as for example with eth it happens like this:

![Screenshot 2022-04-08 at 11 51 09](https://user-images.githubusercontent.com/97019400/162422430-8fde3448-d269-4c7a-80b4-50d866b1de6e.png)

Related [task](https://github.com/status-im/status-desktop/issues/5385)

**Comment by iurimatias** [comment]
moving this here because this is something that should be define in specs & designs

**Comment by alaibe** [comment]
From John:
How many decimal places to display for each currency?
Fiat currencies should always be displayed using the ISO defined no. of decimal places, see https://bit.ly/34eSF71
Stablecoins that are pegged to a fiat currency should always use the same number of decimal places used by the fiat currency it is pegged to.
Number of decimal places for floating crypto currencies are defined by two factors:
1) firstly, always use the minimal number of decimal places needed. There should never be zeros at the end of decimal places e.g. “2.4 ETH” is correct and “2.40 ETH is incorrect.
2) secondly, the maximum number of decimal places should be defined as the number of decimal places needed so that a “1” in the final decimal place always has a value of between $0.01 and $0.10 USD. e.g. when ETH is priced at $365 four decimal places should be used for ETH because 0.0001 ETH = $0.036 USD which is between $0.01 and $0.10 USD. When ETH rises to $1,000 USD, the UI should change to displaying ETH to five digits. To give another example when 1 SNT is worth $0.024860 USD, no decimal places should be used when displaying sums in SNT because 1 SNT = $0.024 which is between $0.01 and $0.10 USD.

**Comment by alaibe** [comment]
Closing as this is WIP
